[2019-01-17 00:59:38,292-INFO: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)]
[2019-01-18 10:29:01,913-INFO: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)]
[2019-01-18 10:35:16,821-INFO: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)]
[2019-01-18 10:35:29,670-ERROR:Exception on /score [GET]]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".\controller.py", line 98, in score
    return render_template('score.html',jy=display)
NameError: global name 'render_template' is not defined
[2019-01-18 10:35:29,782-INFO:127.0.0.1 - - [18/Jan/2019 10:35:29] "GET /score HTTP/1.1" 500 -]
[2019-01-18 10:35:29,948-INFO:127.0.0.1 - - [18/Jan/2019 10:35:29] "GET /favicon.ico HTTP/1.1" 404 -]
[2019-01-18 10:39:59,513-INFO: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)]
[2019-01-18 10:40:05,410-INFO:127.0.0.1 - - [18/Jan/2019 10:40:05] "GET /score HTTP/1.1" 200 -]
[2019-01-18 10:42:54,792-INFO:127.0.0.1 - - [18/Jan/2019 10:42:54] "GET /score HTTP/1.1" 200 -]
